//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbGymEntities : DbContext
    {
        public dbGymEntities()
            : base("name=dbGymEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Egresos> Egresos { get; set; }
        public virtual DbSet<Ingresos> Ingresos { get; set; }
        public virtual DbSet<Membresias> Membresias { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Registro> Registro { get; set; }
        public virtual DbSet<UserMembresias> UserMembresias { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
    }
}
