//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApp.Models
{
    using System.ComponentModel.DataAnnotations;
    public partial class Products
    {
        public int id { get; set; }
        [MaxLength(50)]
        [Required]
        [Display(Name="Nombre")]
        public string Name { get; set; }
        [DataType(DataType.Currency)]
        [Display(Name = "Precio")]
        public double Price { get; set; }
        [Display(Name = "Cantidad")]
        public int Quantity { get; set; }
        [DataType(DataType.Text)]
        [MaxLength(150)]
        [Display(Name = "Descripción")]
        public string Description { get; set; }
    }
}
