//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int id { get; set; }
        public int accessControUser { get; set; }
        public string idUser { get; set; }
        public System.DateTime date { get; set; }
    }
}
