//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace GymApp.Models
{
    public partial class Registro
    {
        public int id { get; set; }
        [Display(Name = "Número de Membresia")]
        public int accessControUser { get; set; }
        public string idUser { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
