//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class RendimientoEjercicio
    {
        public int Id { get; set; }
        [Display(Name = "Ejercicio")]
        public int ejercicioID { get; set; }
        public string userID { get; set; }
        [Display(Name = "Record")]
        public string PR { get; set; }
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha")]
        public System.DateTime fecha { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Ejercicio Ejercicio { get; set; }
    }
}
