//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMembresias
    {
        public int Id { get; set; }
        public string userid { get; set; }
        public int tipoMembresia { get; set; }
        public System.DateTime fInicio { get; set; }
        public System.DateTime ffin { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Membresias Membresias { get; set; }
    }
}
