//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMembresias
    {
        public int Id { get; set; }
        public string userid { get; set; }
        public int tipoMembresia { get; set; }
        public System.DateTime fInicio { get; set; }
        public System.DateTime ffin { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Membresias Membresias { get; set; }
    }
}
