//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApp.Models
{
    using System.ComponentModel.DataAnnotations;
    public partial class UserMembresias
    {
        public int Id { get; set; }
        public string userid { get; set; }
        [Display(Name = "Tipo de membresia",ShortName ="Membresia")]
        public int tipoMembresia { get; set; }
        [Display(Name = "Fecha de Inicio")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime fInicio { get; set; }
        [Display(Name = "Fecha Fin")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime ffin { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Membresias Membresias { get; set; }
    }
}
